### ISSUE TITLE
Nezobrazují se podřazené pojmy.

### ISSUE THREAD

**Issue by psiotwo** [kbss-cvut/termit-ui#459]
# Popis problému
- Při prohlížení slovníku https://termit.fel.cvut.cz/ipr/#/public/vocabularies/2013?namespace=https://slovn%C3%ADk.gov.cz/legislativn%C3%AD/sb%C3%ADrka/256/ se po rozkliknutí pojmu `pozemek` nezobrazí jeho podřazené pojmy.

![image](https://github.com/kbss-cvut/termit-ui/assets/1140626/d95d10e7-0ddb-46f4-9320-48daabb80328)

**Comment by ledsoft** [comment]
Thanks for reporting this. According to the logs, this is caused by attempting to map a null key EhCache when checking access rights. Here's the relevant part of the stacktrace:
```
at cz.cvut.kbss.termit.service.repository.RepositoryAccessControlListService$$SpringCGLIB$$0.findFor(<generated>)
termit-ipr-prod-backend  | 	at cz.cvut.kbss.termit.service.security.authorization.acl.AccessControlListBasedAuthorizationService.canReadAnonymously(AccessControlListBasedAuthorizationService.java:75)
termit-ipr-prod-backend  | 	at jdk.internal.reflect.GeneratedMethodAccessor48.invoke(Unknown Source)
termit-ipr-prod-backend  | 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
termit-ipr-prod-backend  | 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
termit-ipr-prod-backend  | 	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:351)
termit-ipr-prod-backend  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:196)
termit-ipr-prod-backend  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
termit-ipr-prod-backend  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
termit-ipr-prod-backend  | 	at net.bull.javamelody.MonitoringSpringInterceptor.invoke(MonitoringSpringInterceptor.java:76)
termit-ipr-prod-backend  | 	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:184)
termit-ipr-prod-backend  | 	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:765)
termit-ipr-prod-backend  | 	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:717)
termit-ipr-prod-backend  | 	at cz.cvut.kbss.termit.service.security.authorization.acl.AccessControlListBasedAuthorizationService$$SpringCGLIB$$0.canReadAnonymously(<generated>)
termit-ipr-prod-backend  | 	at cz.cvut.kbss.termit.service.security.authorization.VocabularyAuthorizationService.canRead(VocabularyAuthorizationService.java:157)
```

Will investigate and fix.
